version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    volumes:
      - .:/ysnp
    environment:
      - POSTGRES_USER=ysnp
      - DJANGO_READ_DOT_ENV_FILE=true
    depends_on:
      - redis
      - postgres
    ports:
      - '8000:8000'
    command: /start-dev.sh

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      - POSTGRES_USER=ysnp
    env_file: .env

  redis:
    image: redis

  celeryworker:
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    environment:
      - POSTGRES_USER=ysnp
    command: /start-celeryworker.sh
