version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    volumes:
      - .:/ysnp
    environment:
      - POSTGRES_USER=ysnp
      - DJANGO_READ_DOT_ENV_FILE=true
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - '8000:8000'
    command: /start-dev.sh

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=ysnp

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  celeryworker:
    <<: *django
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: /start-celeryworker-dev.sh
