version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    volumes:
      - .:/ysnp
    ports:
      - '8000:8000'
    command: /start-dev.sh

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  celeryworker:
    <<: *django
    depends_on:
      - rabbitmq
    ports: []
    command: /start-celeryworker-dev.sh
